# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: test1234
  CLOUD_SQL_DATABASE_NAME: khproddb
  CLOUD_SQL_CONNECTION_NAME: lamusic1:us-central1:lamysql
# [END gae_python37_cloudsql_config]